[package]
name = "examples"
version = "0.6.0"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
publish = false

[dependencies]
tehuti = { version = "0.6", path = "../_", features = ["postcard"] }
tehuti-mock = { version = "0.6", path = "../mock" }
tehuti-socket = { version = "0.6", path = "../socket" }
serde = { version = "1", features = ["derive"] }
